### ISSUE TITLE
Add graph creation functionality using weather-model-graphs

### ISSUE THREAD

**Issue by sadamov** [mllam/neural-lam#83]
### Overview
This PR adds functionality to create and save different graph architectures using the `weather-model-graphs` package. The implementation includes support for three graph types (currently):
- Keisler graphs (single-scale mesh)
- GraphCast (multi-scale)
- Oskarsson hierarchical graphs

*Reference*
https://github.com/mllam/neural-lam/pull/66#issuecomment-2434482120

### New Features
- Script to generate graphs from datastore xy coordinates
- Integration with `weather-model-graphs` package
- Support for multiple datastore types (MDP, NPYFilesMEPS)
- Graph serialization to PyTorch format

### Implementation Details
```python
from pathlib import Path
import weather_model_graphs as wmg
from neural_lam.datastore import init_datastore

def create_graphs(datastore):
    xy = datastore.get_xy("state", stacked=False)
    graphs = {
        'keisler': wmg.create.archetype.create_keisler_graph(xy_grid=xy),
        'graphcast': wmg.create.archetype.create_graphcast_graph(xy_grid=xy),
        'hierarchical': wmg.create.archetype.create_oscarsson_hierarchical_graph(xy_grid=xy)
    }
    return graphs
```

### Known Issues
1. Graph serialization with `wmg.save.to_pyg()` not working correctly
2. Need to determine correct edge/node feature naming convention

### TODO
- [ ] Expand/simplify PyG serialization
- [ ] Adapt tests for graph creation with wgm
- [ ] Document graph properties and usage

### Questions
1. What's the preferred format for storing generated graphs?
2. Should we include visualization tools?
3. How closely do we want to interate `wgm` into `nl` (slang for neural-lam, obviously)

**Comment by joeloskarsson** [comment]
I will take this on, as there is a need to more tightly integrate neural-lam and wmg for #84 . Or, in particular, neural-lam will have to call wmg with specific arguments, so we can add a dependency from neural-lam to wmg and then graph-creation scripts in neural-lam that call wmg. 

For #84 this will be needed to impose a specific ordering between interior grid nodes and boundary grid nodes. By calling wmg directly from neural-lam we can assure that these calls always place all interior nodes before all boundary nodes.

**Comment by muskan-1301** [comment]
Hi @joeloskarsson I see this issue has been open for a while and I'm interested in helping move it forward. I've been looking at the weather-model-graphs package and the proposed integration.

Would it be helpful if I started with a draft PR implementing one graph type (maybe Keisler) to get the ball rolling? Happy to pick up where this left off.

**Comment by joeloskarsson** [comment]
@leifdenby this was my script for calling wmg: https://github.com/joeloskarsson/neural-lam-dev/blob/research/neural_lam/build_rectangular_graph.py It should be possible to simplify and improve a bit now

**Comment by Sharkyii** [comment]
@joeloskarsson @sadamov  I would like to add a graph creation module that uses the weather-model-graphs (wmg) package.
This will allow creating all the mentioned graph types and exporting them to PyG format, while ensuring compatibility with existing datastores (MDP, NPYFilesMEPS).

**Working**
- Add a --graph-type flag for selecting the graph type
- Use wmg to build graphs from datastore xy coordinates
- The (Nx, Ny, 2) array from datastore.get_xy(stacked=False) must be reshaped to (Nx * Ny, 2) before passing to wmg
- wmg returns a single networkx.DiGraph with an edge attribute component: "g2m", "m2g", "m2m" , "mesh_up", "mesh_down" (for hierarchical graphs)
- Use wmg.split_graph_by_edge_attribute to split into component subgraphs


**Serialization**

wmg.save.to_pyg() serializes graphs to PyG format, but it is currently not working correctly
Therefore, custom serialization will be implemented, mirroring existing helpers like save_edges / save_edges_list

**Storage Format**
- Stick with the existing .pt format using torch.save.
- This is required because load_graph() in utils.py is used during training and expects graphs in this exact format.

**Visualization**

No new visualization tooling is needed. Since wmg works with networkx.DiGraph objects before serialization:
- We can use wmg.visualise, or Reuse the existing plot_graph() in create_graph.py neural-lam already includes Plotly and plot_graph.py for visualization.

So, the wmg pipeline can simply reuse the existing --plot flag without adding new tools.

**Comment by sadamov** [comment]
superceded by #384
